name = "zero-waste-quiz"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

# Build command removed for development

[vars]
JWT_SECRET = "your-development-jwt-secret"

[env.development]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
AUDIO_RETENTION_DAYS = "1"
DATA_RETENTION_DAYS = "30"
GDPR_COMPLIANCE_MODE = "true"

[[env.development.d1_databases]]
binding = "DB"
database_name = "zero-waste-quiz-dev"
database_id = "your-dev-d1-database-id"
preview_database_id = "preview-db"

[env.production]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
AUDIO_RETENTION_DAYS = "0"
DATA_RETENTION_DAYS = "365"
GDPR_COMPLIANCE_MODE = "true"

[[env.production.d1_databases]]
binding = "DB"
database_name = "zero-waste-quiz-prod"
database_id = "your-prod-d1-database-id"

[[env.production.durable_objects.bindings]]
name = "SESSION_MANAGER"
class_name = "SessionManager"

[[env.production.durable_objects.bindings]]
name = "LEADERBOARD_BROADCASTER"
class_name = "LeaderboardBroadcaster"

[durable_objects]
bindings = [
  { name = "SESSION_MANAGER", class_name = "SessionManager" },
  { name = "LEADERBOARD_BROADCASTER", class_name = "LeaderboardBroadcaster" }
]

[[migrations]]
tag = "v1"
new_classes = ["SessionManager", "LeaderboardBroadcaster"]